#!/bin/bash

set -e

DOWNLOAD_URL='http://ftp.gnu.org/gnu/gcc/gcc-4.8.2/gcc-4.8.2.tar.gz'
EXTRACTNAME='gcc-4.8.2'

PKG='gcc'
TGT='powerpc-wrs-vxworks'
CURDIR=`pwd`
PDIR=$(dirname "$CURDIR")

VERSION_FULL=`dpkg-parsechangelog -c1 | grep Version | cut "-d " -f 2`
TMP="echo $VERSION_FULL | tr '-' '\\n'"
if [ "`eval $TMP | wc -l`" = "1" ] ; then
    REVISION=""
    VERSION=$VERSION_FULL
else
    REVISION=`eval $TMP | tail -1`
    VERSION=`eval $TMP | head -n -1 | tr '\n' '-'`
    VERSION=${VERSION%?} # get rid of extra dash at end
fi
unset TMP

BUILDDIR="$CURDIR/build"
NEWSRCDIR="$BUILDDIR/$PKG-$TGT-$VERSION"
ORIG_ARCHIVE="$BUILDDIR/$PKG-${TGT}_$VERSION.orig.tar.gz"

mkdir -p "$BUILDDIR"

#get/extract source
if [ ! -f "$ORIG_ARCHIVE" ] ; then
    rm -rf "$NEWSRCDIR"
    wget -O "$ORIG_ARCHIVE" --no-check-certificate "$DOWNLOAD_URL"
    cd "$BUILDDIR"
    echo Extracting source...
    tar -xf "$ORIG_ARCHIVE"
    rm "$ORIG_ARCHIVE"
    mv "$EXTRACTNAME" "$NEWSRCDIR"
    cd "$NEWSRCDIR"
    ./contrib/download_prerequisites
    cd .. #so that $NEWSRCDIR is in the current directory
    echo Building new orig archive...
    tar -czf "$ORIG_ARCHIVE" "$(basename "$NEWSRCDIR")"
    cd "$CURDIR"
    echo Copying debian files into build tree
    cp -a debian "$NEWSRCDIR"
fi

cd "$NEWSRCDIR"


if [ $# -eq 1 ] ; then
    if [ $1 -eq 32 ] ; then
        echo i686-pc-linux-gnu > ../host
        ARCH_FLAG="-ai386"
    elif [ $1 -eq 64 ] ; then
        echo x86_64-unknown-linux-gnu > ../host
        ARCH_FLAG="-aamd64"
    fi
else
    ./config.guess > ../host
fi

debuild -e WIND_BASE $ARCH_FLAG

